# Generated by Django 5.0.4 on 2024-05-07 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField()),
                ('car_condition', models.CharField(choices=[('Хорошее', 'Хорошее'), ('После ремонта', 'После ремонта'), ('Требуется ремонт', 'Требуется ремонт')], max_length=50)),
                ('car_owners', models.IntegerField()),
                ('Description', models.TextField(max_length=200)),
                ('car_type', models.CharField(choices=[('Купе', 'Купе'), ('Хэтчбек', 'Хэтчбек'), ('Лифтбек', 'Лифтбек'), ('Фастбек', 'Фастбек'), ('Универсал', 'Универсал'), ('Кроссовер', 'Кроссовер'), ('Внедорожник', 'Внедорожник')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('Characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.characteristics')),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('cars', models.ManyToManyField(blank=True, null=True, to='main_page.car')),
                ('managers', models.ManyToManyField(blank=True, null=True, to='main_page.managers')),
            ],
        ),
    ]
