# Generated by Django 5.0.4 on 2024-05-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_characteristics_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='car_type',
            field=models.CharField(choices=[('Купе', 'Купе'), ('Седан', 'Седан'), ('Хэтчбек', 'Хэтчбек'), ('Лифтбек', 'Лифтбек'), ('Фастбек', 'Фастбек'), ('Универсал', 'Универсал'), ('Кроссовер', 'Кроссовер'), ('Внедорожник', 'Внедорожник')], max_length=50),
        ),
    ]
