# Generated by Django 5.0.4 on 2024-05-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_characteristics_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristics',
            name='car_type',
            field=models.CharField(choices=[('Купе', 'Купе'), ('Пикап', 'Пикап'), ('Седан', 'Седан'), ('Хэтчбек', 'Хэтчбек'), ('Лифтбек', 'Лифтбек'), ('Фастбек', 'Фастбек'), ('Универсал', 'Универсал'), ('Кроссовер', 'Кроссовер'), ('Внедорожник', 'Внедорожник')], max_length=50),
        ),
    ]
