# Generated by Django 5.0.4 on 2024-05-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_alter_characteristics_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='selected_car',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
