# Generated by Django 5.0.4 on 2024-05-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_applications_selected_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('Отправлено', 'Отправлено'), ('На рассмотрении', 'На рассмотрении'), ('Принято', 'Принято')], default='Отправлено', max_length=20),
        ),
    ]
